export enum EventType {
  USER_SIGNED_UP = 'USER_SIGNED_UP',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  WORKOUT_UPLOADED = 'WORKOUT_UPLOADED',
  WORKOUT_VERIFIED = 'WORKOUT_VERIFIED',
  WORKOUT_REJECTED = 'WORKOUT_REJECTED',
  STREAK_UPDATED = 'STREAK_UPDATED',
  STREAK_AT_RISK = 'STREAK_AT_RISK',
  STREAK_BROKEN = 'STREAK_BROKEN',
  STREAK_RECOVERED = 'STREAK_RECOVERED',
  FEED_POST_CREATED = 'FEED_POST_CREATED',
  STORY_PUBLISHED = 'STORY_PUBLISHED',
  STORY_GENERATED = 'STORY_GENERATED',
  STORY_SHARED = 'STORY_SHARED',
  FRIEND_REQUEST_SENT = 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REMOVED = 'FRIEND_REMOVED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  SNAP_SENT = 'SNAP_SENT',
  SNAP_RECEIVED = 'SNAP_RECEIVED',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
}

export interface DomainEvent {
  id: string
  type: EventType
  userId: string
  timestamp: Date
  payload: Record<string, unknown>
  metadata?: {
    source: string
    correlationId?: string
  }
}
